/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import static view.ArrayDB.listaServico;

/**
 *
 * @author Alunos
 */
public class gestaoDB extends javax.swing.JFrame {

    int mousePX, mousePY;
    
    public gestaoDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        exitProgram = new javax.swing.JLabel();
        toolbarWindow = new javax.swing.JLabel();
        fundoPrograma = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SLE - Serviço de Logística Empresarial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        panelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseIcon.png"))); // NOI18N
        exitProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitProgramMouseClicked(evt);
            }
        });
        panelFundo.add(exitProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 2, 30, 40));

        toolbarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolbarWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarWindowMouseDragged(evt);
            }
        });
        toolbarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarWindowMousePressed(evt);
            }
        });
        panelFundo.add(toolbarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        fundoPrograma.setLayout(null);
        fundoPrograma.add(jTextField3);
        jTextField3.setBounds(12, 96, 204, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar Registro");
        fundoPrograma.add(jLabel1);
        jLabel1.setBounds(12, 13, 204, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chaves:");
        fundoPrograma.add(jLabel2);
        jLabel2.setBounds(12, 72, 50, 17);
        fundoPrograma.add(jTextField4);
        jTextField4.setBounds(12, 171, 204, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Professor:");
        jLabel3.setToolTipText("");
        fundoPrograma.add(jLabel3);
        jLabel3.setBounds(12, 147, 62, 17);
        fundoPrograma.add(jTextField5);
        jTextField5.setBounds(12, 246, 204, 44);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Objeto:");
        jLabel4.setToolTipText("");
        fundoPrograma.add(jLabel4);
        jLabel4.setBounds(12, 222, 47, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Remover Registro");
        fundoPrograma.add(jLabel5);
        jLabel5.setBounds(564, 13, 204, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Chaves:");
        fundoPrograma.add(jLabel6);
        jLabel6.setBounds(564, 72, 50, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Professor:");
        jLabel7.setToolTipText("");
        fundoPrograma.add(jLabel7);
        jLabel7.setBounds(564, 147, 62, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Objeto:");
        jLabel8.setToolTipText("");
        fundoPrograma.add(jLabel8);
        jLabel8.setBounds(564, 222, 47, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Chaves", " " }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        fundoPrograma.add(jComboBox1);
        jComboBox1.setBounds(564, 96, 204, 44);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Professor", " ", " " }));
        fundoPrograma.add(jComboBox2);
        jComboBox2.setBounds(564, 171, 204, 44);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Objeto", " " }));
        fundoPrograma.add(jComboBox3);
        jComboBox3.setBounds(564, 246, 204, 44);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fundoPrograma.add(jButton1);
        jButton1.setBounds(223, 96, 90, 44);

        jButton2.setText("Registrar");
        fundoPrograma.add(jButton2);
        jButton2.setBounds(223, 171, 90, 44);

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fundoPrograma.add(jButton3);
        jButton3.setBounds(223, 246, 90, 44);

        jButton5.setText("Remover");
        fundoPrograma.add(jButton5);
        jButton5.setBounds(465, 94, 90, 50);

        jButton6.setText("Remover");
        fundoPrograma.add(jButton6);
        jButton6.setBounds(465, 246, 90, 44);

        jButton7.setText("Remover");
        fundoPrograma.add(jButton7);
        jButton7.setBounds(465, 171, 90, 44);

        panelFundo.add(fundoPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 490));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SchoolGround.jpg"))); // NOI18N
        lblFundo.setToolTipText("");
        panelFundo.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toolbarWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarWindowMouseDragged
        System.out.println("Pegando dados brutos de posição da janela.");
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();
        System.out.println("Modificando posição da janela.");
        this.setLocation(coordX-mousePX, coordY-mousePY);
    }//GEN-LAST:event_toolbarWindowMouseDragged

    private void toolbarWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarWindowMousePressed
        System.out.println("Pegando dados brutos de posição do mouse.");
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_toolbarWindowMousePressed

    private void exitProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitProgramMouseClicked
        System.out.println("Encerrando programa.");
        System.exit(0);
    }//GEN-LAST:event_exitProgramMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String chave = jTextField3.getText();
        ArrayDB.listaServico.add(new ArrayDB(chave));
        ArrayDB aux = null;
        for(ArrayDB item : listaServico){
            aux = item;
            System.out.println(item + "\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String chave = jTextField4.getText();
        ArrayDB.listaServico.add(new ArrayDB(chave));
        for(ArrayDB item : listaServico){
            System.out.println(item + "\n");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        for(ArrayDB item : listaServico){
            String aux = item.toString();
            jComboBox1.addItem(aux);
        }
    }//GEN-LAST:event_jComboBox1MouseEntered
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestaoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestaoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestaoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestaoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestaoDB().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitProgram;
    private javax.swing.JPanel fundoPrograma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JLabel toolbarWindow;
    // End of variables declaration//GEN-END:variables
}
