/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Alunos
 */
public class mainMenu extends javax.swing.JFrame {

    int mousePX, mousePY;
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        exitProgram = new javax.swing.JLabel();
        toolbarWindow = new javax.swing.JLabel();
        panelSelector = new javax.swing.JPanel();
        panelGestao = new javax.swing.JPanel();
        lblGestao = new javax.swing.JLabel();
        lblIconeGestao = new javax.swing.JLabel();
        panelFinanceiro = new javax.swing.JPanel();
        lblFinanceiro = new javax.swing.JLabel();
        lblIconeFinancia = new javax.swing.JLabel();
        panelDataBase = new javax.swing.JPanel();
        lblDataBase = new javax.swing.JLabel();
        lblIconeDataBase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SLE - Serviço de Logística Empresarial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        panelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseIcon.png"))); // NOI18N
        exitProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitProgramMouseClicked(evt);
            }
        });
        panelFundo.add(exitProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 2, 30, 40));

        toolbarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolbarWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarWindowMouseDragged(evt);
            }
        });
        toolbarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarWindowMousePressed(evt);
            }
        });
        panelFundo.add(toolbarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        panelSelector.setBackground(new java.awt.Color(204, 204, 204));
        panelSelector.setForeground(new java.awt.Color(255, 255, 255));

        panelGestao.setBackground(new java.awt.Color(153, 153, 153));
        panelGestao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelGestao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGestaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGestaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGestaoMouseExited(evt);
            }
        });

        lblGestao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblGestao.setForeground(new java.awt.Color(255, 255, 255));
        lblGestao.setText("G. de Chaves");

        lblIconeGestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManageIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelGestaoLayout = new javax.swing.GroupLayout(panelGestao);
        panelGestao.setLayout(panelGestaoLayout);
        panelGestaoLayout.setHorizontalGroup(
            panelGestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconeGestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelGestaoLayout.setVerticalGroup(
            panelGestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGestaoLayout.createSequentialGroup()
                        .addComponent(lblIconeGestao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelFinanceiro.setBackground(new java.awt.Color(153, 153, 153));
        panelFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFinanceiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFinanceiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFinanceiroMouseExited(evt);
            }
        });

        lblFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFinanceiro.setForeground(new java.awt.Color(255, 255, 255));
        lblFinanceiro.setText("G. de Itens");

        lblIconeFinancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ItemsIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelFinanceiroLayout = new javax.swing.GroupLayout(panelFinanceiro);
        panelFinanceiro.setLayout(panelFinanceiroLayout);
        panelFinanceiroLayout.setHorizontalGroup(
            panelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconeFinancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFinanceiroLayout.setVerticalGroup(
            panelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinanceiroLayout.createSequentialGroup()
                        .addComponent(lblIconeFinancia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelDataBase.setBackground(new java.awt.Color(153, 153, 153));
        panelDataBase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelDataBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDataBaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDataBaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDataBaseMouseExited(evt);
            }
        });

        lblDataBase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDataBase.setForeground(new java.awt.Color(255, 255, 255));
        lblDataBase.setText("Banco de Dados");

        lblIconeDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DataBaseIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelDataBaseLayout = new javax.swing.GroupLayout(panelDataBase);
        panelDataBase.setLayout(panelDataBaseLayout);
        panelDataBaseLayout.setHorizontalGroup(
            panelDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconeDataBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataBaseLayout.setVerticalGroup(
            panelDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataBaseLayout.createSequentialGroup()
                        .addComponent(lblIconeDataBase)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblDataBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoC.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SLE");

        javax.swing.GroupLayout panelSelectorLayout = new javax.swing.GroupLayout(panelSelector);
        panelSelector.setLayout(panelSelectorLayout);
        panelSelectorLayout.setHorizontalGroup(
            panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDataBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSelectorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSelectorLayout.setVerticalGroup(
            panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(panelGestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panelFundo.add(panelSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SchoolGround.jpg"))); // NOI18N
        lblFundo.setToolTipText("");
        panelFundo.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toolbarWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarWindowMouseDragged
        System.out.println("Pegando dados brutos de posição da janela.");
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();
        System.out.println("Modificando posição da janela.");
        this.setLocation(coordX-mousePX, coordY-mousePY);
    }//GEN-LAST:event_toolbarWindowMouseDragged

    private void toolbarWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarWindowMousePressed
        System.out.println("Pegando dados brutos de posição do mouse.");
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_toolbarWindowMousePressed

    private void exitProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitProgramMouseClicked
        System.out.println("Encerrando programa.");
        System.exit(0);
    }//GEN-LAST:event_exitProgramMouseClicked

    private void panelGestaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGestaoMouseEntered
        panelGestao.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_panelGestaoMouseEntered

    private void panelGestaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGestaoMouseExited
        panelGestao.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panelGestaoMouseExited

    private void panelFinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinanceiroMouseEntered
        panelFinanceiro.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_panelFinanceiroMouseEntered

    private void panelFinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinanceiroMouseExited
        panelFinanceiro.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panelFinanceiroMouseExited

    private void panelDataBaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataBaseMouseEntered
        panelDataBase.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_panelDataBaseMouseEntered

    private void panelDataBaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataBaseMouseExited
        panelDataBase.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_panelDataBaseMouseExited

    private void panelGestaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGestaoMouseClicked
        gestaoObj gC = new gestaoObj();
        gC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelGestaoMouseClicked

    private void panelFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinanceiroMouseClicked
        gestaoChave gI = new gestaoChave();
        gI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelFinanceiroMouseClicked

    private void panelDataBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataBaseMouseClicked
        gestaoDB gDB = new gestaoDB();
        gDB .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelDataBaseMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDataBase;
    private javax.swing.JLabel lblFinanceiro;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblGestao;
    private javax.swing.JLabel lblIconeDataBase;
    private javax.swing.JLabel lblIconeFinancia;
    private javax.swing.JLabel lblIconeGestao;
    private javax.swing.JPanel panelDataBase;
    private javax.swing.JPanel panelFinanceiro;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPanel panelGestao;
    private javax.swing.JPanel panelSelector;
    private javax.swing.JLabel toolbarWindow;
    // End of variables declaration//GEN-END:variables
}
